### ISSUE TITLE
Integrate sphinx migrations. 

### ISSUE THREAD

**Issue by Tjoosten** [ActivismeBE-archive/ACTIE-ontbinding-nato#36]
For the database management between releases. 

**TODO:**

- [x] Install Phinx. 
- [x] Initialize phinx migration config. 
- [x] Write script for composer to place a new config file. 
- [ ] Write the database ERD migrations
- [ ] Write the database seeds.

**Comment by Tjoosten** [comment]
Word niet meer verder aan ontwikkeld omdat laravel standaard een eigen systeem heeft hiervoor
